### ISSUE TITLE
Action datatype reform

### ISSUE THREAD

**Issue by sopvop** [lpsmith/postgresql-simple#120]
For building complex values, like rows or whole queries from small bits. I think it would be better if
Action was actually a dlist. 

``` haskell
data ActionStep = Plain Builder Action
                | Escape ByteString Action
                | ...
                | End

type Action = ActionStep -> ActionStep

many:: [Action] -> Action
many = mconcat

class ToField a where
    toField :: a -> Action
```

pros:
- It should be a bit lazier in the good sense, with less allocations and thus gc (for some values).
- Monoid interface is easy to use.

cons:
- breaking interface, but easy to fix

**Comment by s9gf4ult** [comment]
Hello guys. 

You are talking here about new quasiquoter? I have some for you:

```haskell
let subquery = [sqlExp| SELECT field, field2 FROM table where name = #{name}|]
pgQueryB [sqlExp| SELECT * FROM (^{buquery}) WHERE field = #{fieldValue}|] 
```

It supports two ways of interpolating: 

1. `^{sqlBuilder}` which requires `sqlBuilder` to be an instance of `ToSqlBuilder`. This is equivalent of `mappend` on `SqlBuilder`
2. `#{value}` which requires `value` to be an instance of `ToField`. This is equvalent of current interpolation of `Query` with `?` sign inside.

The returning value of this quasiquoter is https://bitbucket.org/3ai/pgsimple/src/e217ee4adf29a9c76cfa68c0d09799e1de74c56e/src/PGSimple/SqlBuilder.hs?at=master

```haskell
newtype SqlBuilder =
    SqlBuilder
    { sqlBuild :: Connection -> IO Builder }
    deriving (Typeable, Generic)

instance Monoid SqlBuilder ...
```

Note that there is instance: 

```haskell
instance ToRow row => ToSqlBuilder (Query, row) where
    toSqlBuilder (q, row) = SqlBuilder $ \c ->
        fromByteString <$> formatQuery c q row
```

Which will give us this: 

```haskell
query :: (ToSqlBuilder q, FromRow r) => Connection -> q -> IO [r]
```

instead of 

```haskell
query :: (ToRow q, FromRow r) => Connection -> Query -> q -> IO [r] 
```

And we could write queries like 

```haskell
query con [sqlExp| SELECT id, name FROM tbl WHERE name = #{name}|] 
```

As well as 

```haskell
query con ("SELECT id, name FROM tbl WHERE name = ?", [name])
```

for old-style people.

There is also `PgMonadT` and typeclass `PgMonad` https://bitbucket.org/3ai/pgsimple/src/e217ee4adf29a9c76cfa68c0d09799e1de74c56e/src/PGSimple/Types.hs?at=master#cl-144 which could be integrated to `postgresql-simple` but I thing it should be done like: 

```haskell 
class HasPostgres m where
    getPostgress :: m Connection

instance (HasPostgres m) => HasPostgres (ReaderT m) ... 
instance (HasPostgres m) => HasPostgres (MaybeT m) ...
...

pgQuery :: (ToSqlBuilder q, HasPostgres m, FromRow r) => q -> m [r]
.... 
```

And remove this stupid typeclass

```haskell 
class (Monad m) => PgMonad m where
    mQuery               :: (ToRow q, FromRow r) => Query ->  q  -> m [r]
    mQueryB              :: (FromRow r)          => SqlBuilder  -> m [r]
....
```

What do you think?

**Comment by sopvop** [comment]
Here is [gist](https://gist.github.com/sopvop/05363f5f0ef51de6f06e) with quick implementation of pure escaping in haskell.
As we discussed with @lpsmith on IRC, it uses the extended string format for strings.

There are 3 different functions for bytea escaping. I think the escapeByteAFast would be preferable.
I think someone proficient with Builder can optimize this even further.

**Comment by lpsmith** [comment]
Yeah,  it looks like a good proof of concept,  and after our discussion I do believe I understand quoting completely.  I'm confident that we can faithfully re-implement libpq's identifier and value quoters for the extended escape syntax,   at least on `utf8` character encodings.

Supporting other character encodings would be considerably more difficult,   but  `postgresql-simple` already assumes utf8 encodings,  in places I'm aware of and probably in a few places I'm not.     However,  the difference here is that there are clear security issues that might arise from the use of `postgresql-simple` in the wrong deployment environment.

Every database specifies an encoding it uses internally,  which is set at `createdb` time and is expensive to change.   Clients can also specify an encoding that it's using,   subject to compatibility restrictions with the database encoding.     It turns out that clients can set `utf8` on everything except MULE internal code,  which is the multilingual extensions for GNU Emacs.    This is a sufficiently esoteric option that I wasn't aware it even existed,  I seriously doubt that many people use,  and that I honestly don't care if we can't support it.

So my idea is that we should `SET client_encoding TO 'utf8'` at connection initialization;  presumably this would result in an exception if the database encoding is MULE.    So this should keep us secure in any deployment environment.

**Comment by lpsmith** [comment]
My apologies for not getting to this issue in 0.5,  sopvop;  this issue will be a top priority for 0.6.    But 0.5 was really dragging out and,  I fear, substantially inconveniencing some of the people who contributed good changes and bugfixes months ago.

Although,  a good starting point might be to tackle #127 first,  and implement some pure escaping functions,  which can be done without a major point release,  and then change the interface itself.
