### ISSUE TITLE
Missing ToField instance for Rational

### ISSUE THREAD

**Issue by sol** [lpsmith/postgresql-simple#146]
There is a `FromField` instances for `Rational`, but no `ToField` instance.  Is there a good reason why we do not want that instance, or is it just not implemented yet?

**Comment by lpsmith** [comment]
I'm not aware of a good reason... probably just not implemented yet.

**Comment by lpsmith** [comment]
Actually, I can think of one significant complication:   where do you truncate or round a repeating decimal?

Since there isn't an obviously correct answer,  you'd probably want to simply generate a division and let postgresql do the conversion for us,  because we don't really have any way of knowing what type the rational is going to be converted to.

I don't know if we'd want to generate the decimal syntax in the case of a terminating decimal.

**Comment by lpsmith** [comment]
Another potentially complicating factor with the division approach is the fact that,  just like the python2 flaw that was fixed in python3, postgresql performs ad-hoc overloading on `/` to mean both integer division and non-integer division, depending on types.

~~~
$ psql
psql (9.4.1)
Type "help" for help.

lpsmith=> select (435 / 10) :: int;
 int4 
------
   43
(1 row)

lpsmith=> select (435 / 10) :: float;
 float8 
--------
     43
(1 row)

lpsmith=> select (435.0 / 10.0) :: float;
 float8 
--------
   43.5
(1 row)

lpsmith=> select (435.0 / 10.0) :: integer;
 int4 
------
   44
(1 row)
~~~

So,  hmm,  we should probably generate a `.0` after each number.  (Or maybe just one suffices?)

**Comment by lpsmith** [comment]
Another issue to investigate is how this interacts with postgresql's `numeric` type.   I don't know enough about how postgresql's (fairly wonky) type inference handles cases like these:  on the one hand,  we do want accurate conversions to numeric,   on the other hand numeric is slow so we don't want all conversions to go through it either,  as numeric is slow.

I'm thinking that postgresql almost has to interpret `10.0` as `unknown`,  so that  `select (1.0 / 3.0) :: numeric`  is using `(/) :: numeric -> numeric -> numeric`,   while `select (1.0 / 3.0) :: float`  is using `(/) ::  float -> float -> float`.    Which would also be perfect for what we want,   but this hypothesis also needs verification.

**Comment by lpsmith** [comment]
So,  yeah,  my hypothesis isn't accurate enough,  I'm afraid:

~~~
lpsmith=> select (2.0 / 3.0) :: numeric(100,40);
                  numeric                   
--------------------------------------------
 0.6666666666666666666700000000000000000000
(1 row)

lpsmith=> select (2.0 / 3.0 :: numeric(100,40))
lpsmith-> ;
                  ?column?                  
--------------------------------------------
 0.6666666666666666666666666666666666666667
(1 row)
~~~

That's unfortunate.

**Comment by lpsmith** [comment]
So yeah,  I don't really see any good options here;  we'd have more options if postgresql-simple had a better idea of what the postgresql types of the parameters were.    But as it stands,  unless you are using the `pgmp` extensions,  there really isn't a particularly good syntax to generate that would fit all cases;   it seems that you probably do want to specify in some greater detail how to handle the conversions.

(I would like to add support for `pgmp`,  by the way,  as I mentioned in #94.)

**Comment by sol** [comment]
It's fine for me to close this issue, if don't have any good options to implement his right now.

**Comment by lpsmith** [comment]
Yeah,  I don't see a way to support this to my satisfaction,  for the foreseeable future.    I'll keep it mind as something to revisit when/if we ever add support for pgmp.
