### ISSUE TITLE
Array support for composite types

### ISSUE THREAD

**Issue by timmytofu** [lpsmith/postgresql-simple#159]
Semi-related, or at least mentioned, in #153 

Right now, the fromArray function passes the same field information to the fieldParser, even though the field is an array and the fieldParser would be parsing only a subset of that with a different type.

I started looking into it but the full nature of `Field`, how `typeinfo` works etc. I haven't had time to dig into yet.

**Comment by lpsmith** [comment]
What exactly do you mean?   Do you want to parse a postgresql result that corresponds to something like `(Text, [Int])`, or `[(Text,Int)]`?

Since the syntax emitted by postgres for a given type can vary slightly depending on context,  one of the current limitations of `postgresql-simple` is that parsing these oddball contexts in a compositional way can't be as efficient as one desires,  as we have to massage the syntax before we feed it into the next parser in the chain.     The current `Range` module takes this approach for example.

Also,  its fairly straightforward in specific cases,  if a little tedious,  to avoid having to deal with composite types as long as they are a scalar,  and not an array.    This is because in these cases,  one can ask the backend to unpack the composite type into multiple fields,  and send the result in a format that's more amenable to the current state of postgresql-simple.    However, most cases where you have an array of composite types can't be so easily worked around,  which makes handling the `[(Text,Int)]` case significantly more interesting than the `(Text, [Int])` case.

**Comment by timmytofu** [comment]
Something like [(Text,Int)]

Here's an example:

```
{-# LANGUAGE DeriveDataTypeable            #-}
{-# LANGUAGE OverloadedStrings             #-}
{-# LANGUAGE ScopedTypeVariables           #-}

module Ex where

import           Data.ByteString                      (ByteString)
import           Data.ByteString.Char8                (unpack)
import           Data.Typeable                        (Typeable)
import           Data.Vector                          (Vector)
import           Debug.Trace

import           Database.PostgreSQL.Simple
import           Database.PostgreSQL.Simple.FromField (FromField, fromField
                                                      ,returnError
                                                      ,typeInfo, typename)

-------------------------------------------------------------------------------


data Twofer = Twofer { one :: Integer, two :: Integer }
            deriving (Show, Read, Eq, Typeable)

instance FromField Twofer where
    fromField f Nothing   = returnError UnexpectedNull f ""
    fromField f (Just bs) = do
      typename' <- typename f
      typeinfo  <- typeInfo f
      trace (out bs typename' typeinfo) $
            return (Twofer 1 2) -- return junk, the trace is all we need

out :: Show a => ByteString -> ByteString -> a -> String
out dat tname tinfo = "~~~~~~~~~~\n\ndata to parse = "   ++ unpack dat
                        ++ "\n\ntypename = " ++ unpack tname
                        ++  "\n\ntypeinfo = "     ++ show tinfo
                        ++ "\n\n=========="

main :: IO ()
main = do
  conn <- connect $
            defaultConnectInfo { connectDatabase="sandbox", connectUser="me" }

  _ <- execute_ conn "CREATE TYPE twofer AS (one int, two int);"

  _ <- query_ conn "SELECT '{\"(1,2)\"}'::twofer[];" :: IO [Only Twofer]
  -- the output I get (obvs the OID will be different between machines and
  -- this conversion would fail with a real parser):

  -- data to parse = {"(1,2)"}

  -- typename = _twofer

  -- typeinfo = Array {typoid = Oid 18544, typcategory = 'A', typdelim = ',', typname = "_twofer", typelem = Composite {typoid = Oid 18545, typcategory = 'C', typdelim = ',', typname = "twofer", typrelid = Oid 18543, attributes = fromList [Attribute {attname = "one", atttype = Basic {typoid = Oid 23, typcategory = 'N', typdelim = ',', typname = "int4"}},Attribute {attname = "two", atttype = Basic {typoid = Oid 23, typcategory = 'N', typdelim = ',', typname = "int4"}}]}}


  _ <- query_ conn "SELECT '{\"(1,2)\"}'::twofer[];" :: IO [Only (Vector Twofer)]
  -- I get the _same_ typename and typeinfo from the trace - Twofer's fromField is being
  -- given the _same_ Field data - it's being told to parse something of
  -- array type, but really it's not

  -- data to parse = (1,2)

  -- typename = _twofer

  -- typeinfo = Array {typoid = Oid 18544, typcategory = 'A', typdelim = ',', typname = "_twofer", typelem = Composite {typoid = Oid 18545, typcategory = 'C', typdelim = ',', typname = "twofer", typrelid = Oid 18543, attributes = fromList [Attribute {attname = "one", atttype = Basic {typoid = Oid 23, typcategory = 'N', typdelim = ',', typname = "int4"}},Attribute {attname = "two", atttype = Basic {typoid = Oid 23, typcategory = 'N', typdelim = ',', typname = "int4"}}]}}

  _ <- execute_ conn "DROP TYPE twofer;"

  return ()
```

**Comment by timmytofu** [comment]
I saw the three different `ArrayFormat`s, but have only been able to get postgres to produce one. I see the typeInfo is pulled from a connection (if it isn't available already), and looking at `fromArray`:

```
fromArray :: FieldParser a -> TypeInfo -> Field -> Parser (Conversion [a])
fromArray fieldParser typeInfo f = sequence . (parseIt <$>) <$> array delim
  where
    delim = typdelim (typelem typeInfo)
    fElem = f{ typeOid = typoid (typelem typeInfo) }

    parseIt item =
        fieldParser f' $ if item' == "NULL" then Nothing else Just item'
      where
        item' = fmt delim item
        f' | Arrays.Array _ <- item = f
           | otherwise              = fElem
```
It's that `f'` bit, I think. I'm not sure what the discrimination between `ArrayFormat`s in the pattern guard is doing, as stated above, but neither `f` nor `fElem` is going to pass the right info to the sub-parser, I don't believe. fElem will have the right OID, maybe, and will maybe then lookup the info for that id correctly?

**Comment by timmytofu** [comment]
Alright, so it works for e.g. arrays of integers because of the `fElem` bit which replaces the oid (but leaves the name and other info the same) and the check for compatibility (`ok32` via `mkCompats`) looks at only the oid for standard types.

For composite types, though, we don't have a stable oid to work with, and so the typename is a problem. I'm not sure how to solve this though, because typename comes from typeInfo, which takes the whole field, gets the oid, and looks it up as appropriate. This sub-part isn't a proper 'field', per se, though - it's only part of a column, not a full column, and is only a partial result, so filling in the other details of `Field` is weird. All I can think of would be altering the `Field` type to include the typeInfo function :: Conversion TypeInfo and in this case set it to `const (typelem thearray)`

**Comment by timmytofu** [comment]
Alright, I just noticed the `typeInfoByOid` function - that will work in my case, since the fields oid is replaced. I can do `typname . typeInfoByOid . typeOid $ f` to get the proper name. Is that the intended purpose of `typeInfoByOid`? Why does `typeInfo` do it by looking up the oid by result and column (which is then wrong in my case) instead of just taking the oid from the `Field` directly - I guess there must sometimes not be a populated oid? I'm also not sure when the `Array` form of  `ArrayFormat` manifests, in which case the oid would _not_ be replaced and would not be reliable.

**Comment by lpsmith** [comment]
Well,  the column type contains only an Oid because fetching the typeinfo is potentially a little bit expensive.    So there isn't a typeinfo to replace.  The function `typeinfo` is basically just a convenient wrapper around `typeInfoByOid`.

So,  in order to parse arrays of composites,   all you (should) need to do is write a parser for composite types.   You could make this specific to one or a few composite types you specifically need,  or you could try to make this more generic.   IIRC, the array module will remove a layer of escaping before it passes the bytestring onto your parser,  and it replaces the typeOid so that you'll get back the TypeInfo for your composite type when you ask for it via `typeinfo`.

In the generic case,  your parser would hopefully be not unlike the Array parser:   you replace the type oid of the column based on the TypeInfo structure,  calculate the corresponding bytestring by finding the correct `,` character and removing a layer of escaping,  then calling `fromField` with this updated column and data.

At least,  that's how I hope it would work;  I haven't delved into the syntax issues very carefully,  and I'll admit there's some possibility that what's already there might not be quite right.    This whole interface is mostly evolved and certainly a little bit rough once you start peeking behind the curtain.

**Comment by timmytofu** [comment]
> The function typeinfo is basically just a convenient wrapper around typeInfoByOid.

Sorta - it calls `getTypeInfo` on an oid, but it's on the oid it fetches by result and column, which in the case of arrays is wrong (the oid is replaced in the `Field`, but result and column are the same):

```
typeInfo :: Field -> Conversion TypeInfo
typeInfo Field{..} = Conversion $ \conn -> do
                       Ok <$> (getTypeInfo conn =<< PQ.ftype result column)
```

In my case it would work better if it did actually fetch by the oid in the `Field`. I've [made that change](https://github.com/timmytofu/postgresql-simple/commit/bb1e42fcb7f93d129dc63d8d80ad76ab970eb274), and it hasn't broken any tests, but I assume it must've been done this way for a reason originally. If not, LMK and I'll add tests for a composite type and submit a pull request.

**Comment by lpsmith** [comment]
Nope, that looks like a bug to me.  I'd be happy to merge it.

**Comment by lpsmith** [comment]
Ok, I went ahead and merged,  partly I was interested to go through the process of merging somebody else's fork without an explicit PR using the Github UI.

**Comment by lpsmith** [comment]
Ok, I went ahead and merged,  partly I was interested to go through the process of merging somebody else's fork without an explicit PR using the Github UI.

**Comment by timmytofu** [comment]
Thank you, this change will make some sprocs we're writing usable.
