### ISSUE TITLE
Merge functionality from postgresql-transactional?

### ISSUE THREAD

**Issue by BardurArantsson** [lpsmith/postgresql-simple#179]
Just out of curiosity: Would you be willing to consider merging the functionality from [postgresql-transactional](https://github.com/helium/postgresql-transactional) into postgresql-simple? That page has information about the features, but basically it gets you static guarantees that you're not doing something silly wrt. transactions -- like, for example, nesting BEGIN/COMMIT accidentally.

It's a [very simple single-file module](https://github.com/helium/postgresql-transactional/blob/master/src/Database/PostgreSQL/TransactionalStore.hs) which could easily be imported almost verbatim -- they're using "mtl" and postgresql-simple uses "transformers", so that would probably need to be changed, but otherwise it seems pretty straightforward to do.

I suppose ideally and to get the full benefit one might want tighter integration, but it seems to me that even a "dumb" port of the code would be valuable for those of us wanting stronger static guarantees. This can just live on top of the existing postgresql-simple API as an optional module.

What you think?

**Comment by reiddraper** [comment]
:+1: from me.

**Comment by lpsmith** [comment]
Well,  I'd be skeptical of such a move,  but not necessarily deadset against it.

What would the benefit be to postgresql-transactional users be,  to adopting this change?

Also,  fair warning,  at least on this count I'd probably be more inclined to adopt the Scheme community's philosophy,  of making nested use either a dynamic error and/or "fixing" nested use in some way.

**Comment by BardurArantsson** [comment]
If we did the "dumb" integration, I think it'd mostly be convenience and discoverability, but see below.

If we did a thorough integration, they'd also get a boatload of safety-by-default for very little effort and it wouldn't even complicate the API by much.

My motivation is actually not "users" per se, but library developers who want to give `Connection` to users of *their* library. It would be great to have a way to statically say "you must not do any BEGIN/COMMIT on this Connection" in the API of my library.

> Also, fair warning, at least on this count I'd probably be more inclined to adopt the Scheme community's philosophy, of making nested use either a dynamic error and/or "fixing" nested use in some way.

Making it a runtime error would be OK, I guess[1] -- my main desire is to avoid *silent* bugs resulting from improper transaction nesting. I don't think it's possible to "fix" nested use of transactions and still keep any kind of desirable semantics. (Savepoints aren't enough IIRC, though it's been a while since I though about it deeply.)

[1] Though I don't see how you could implement it reasonably without explicit support from libpq (and hopefully without actually querying the database; which would increase latency). Does `libpq` have a way to ask if a transaction is active? Unless that's the case then I think the approach in `postgresql-transaction` is really the best that can be done.

**Comment by sopvop** [comment]
I was thinking about making a `postgresql-simple-lifted` package, by removing snap specific code from snaplet-postgresql-simple. This transaction thing would fit such package.
Unfortunately I don't have much free time lately.

**Comment by lpsmith** [comment]
Well, I'm not sure what kind of deeper integration is possible.    Though regarding lifted operations,  I'm softening on that _somewhat_.    Historically,  I was opposed because the cases that aren't trivial compositions of postgresql-simple operators and `liftIO` require lifted exception handling,  and I was (and still am to an extent) uncomfortable with that due to major shortcomings in and/or lack of understanding on my part of the lifted exception handling options on hackage.

> Making it a runtime error would be OK, I guess[1] -- my main desire is to avoid silent bugs resulting from improper transaction nesting. 

Yeah,  I totally agree,  @reiddraper's Chicago Haskell Users' Group presentation really highlighted this issue in my mind,  as I never really thought through what would happen if `withTransaction` et al were misused.

I actually brought up if there was a way to turn on stricter transaction handling somehow,  ideally as a GUC variable,  in #postgresql on freenodel a few weeks ago.  (ideally, so that the backend would issue an error to the client instead of a warning when "begin" is used inside a transaction,  or abort or commit is used outside.)   One of the regulars there wished that there was.

> Does libpq have a way to ask if a transaction is active?

Yes,  transactionStatus allows you to query a connection object as to whether it is in a transaction or not;  and (perhaps I should double check, but) this doesn't involve a network round-trip.   So it should be possible for postgresql-simple to reasonably efficiently emulate the desired behavior above.

> I don't think it's possible to "fix" nested use of transactions and still keep any kind of desirable semantics. (Savepoints aren't enough IIRC, though it's been a while since I though about it deeply.)

I very much share your concern,  though I'm perhaps slightly less pessimistic about it.   I can think of three probably useful behaviors for a nested `withTransaction`:  it could issue an error,  it could simply execute the inner action without creating another transaction,  or it could use savepoints and the like.   Now,  as a general replacement for `withTransaction`,  I too am deeply uncomfortable with the latter two options,  but I also think they'd be useful in the right situation.

**Comment by BardurArantsson** [comment]
So... any thoughts on how to proceed? Would it make sense to do a proof of concept for (shallow|deep) integration (using "transformers" rather than "mtl"), or are you still leaning towards the run-time solution? (I must say that I honestly think compile-time here is actually both easier *and* more useful here.)

TBH, I'm not sure I understand the bit about lifted exception handling -- all you need for postgresql-transactional is ReaderT and that's pretty "transparent" as far as monad transformers go.

**Comment by lpsmith** [comment]
Well, I'm still not sure what you mean by a "deep" integration.   As for runtime versus postgresql-transactional,   why not both?

Regarding lifted exception handling,  you need it if you want to generalize `withTransaction` to `(MonadIO m, MonadCatch m) => Connection -> m a -> m a`,  and other similar cases arise with e.g. the `fold` family of functions.   Otherwise you only have `MonadIO m => Connection -> IO a -> m a`.

And as it stands,  Snap uses `MonadCatchIO-transformers` (though the not-officially-released snap-1.0 moves to monad-control) while Yesod uses `monad-control`;  the former is obviously broken,  and `monad-control` is perhaps the least bad option though I'm not entirely comfortable with it.

So yes,  the reader monad transformer is very benign compared to some of the other transformers,  but properly lifting postgresql-simple operators involves more than that.

**Comment by BardurArantsson** [comment]
Right, I didn't really explain "deep" integration: It would basically just be about changing type signatures of the existing functions, so `query` would become

    query: (ToRow q, FromRow r) => Connection -> Query -> q -> TransactionM [r] 

(where `TransactionM` ~ `ReaderT Connection IO`, probably hidden behind a newtype.)

Does that make sense?

(Personally, I don't necessarily think generalizing type signatures to e.g. MonadIO (etc.) is worth it. It complicates things quite a bit and all you really gain from it is that users don't have to say `liftIO`.)

**Comment by lpsmith** [comment]
Changing the type signatures from the functions exported from `Database.PostgreSQL.Simple` is a non-starter,  not only because of backwards compatibility,  but also that I feel this change would be fundamentally at odds with the overall philosophy of postgresql-simple.

One of the primary goals of postgresql-simple is to not impose any particular vision of how exactly one interacts with a postgresql database,  but rather to allow any means of interaction allowed by postgres.

Now,  admittedly,  postgresql-simple does fall a bit short of this goal on a few counts,  but that's _mostly_ due to things that are missing rather than imposing opinions on how one should and shouldn't interact with postgres.   (And,  postgres/libpq itself imposes a few rather silly opinions on this topic as well... :-/)  

It would seem to me that forcing everybody to use postgresql-transactional would eliminate several important use cases:

1.   Bare statements

    If you don't run something in an explicit transaction, there's basically an implicit transaction around a single statement,  which means 1 round-trip instead of 3.

2.   Using cursors to stream large quantities of data out of postgres

    Generally speaking,  if you want to use a cursor,  you want to use that cursor inside a single (possibly read-only) transaction,  and you want to do IO while the transaction is ongoing to e.g. send that data along to an http client.

3.   Other cases when you really do want to do IO in the middle of a transaction

    This third use case doesn't crop up that often in my experience,  but I do have examples where I'm interleaving two different transactions across two different postgresql servers for replication purposes,  etc.

> (Personally, I don't necessarily think generalizing type signatures to e.g. MonadIO (etc.) is worth it. It complicates things quite a bit and all you really gain from it is that users don't have to say liftIO.)

Well, I agree somewhat,  except in the cases where you do need lifted exception handling,  because in the most general case, I don't think you can turn `withTransaction :: Connection -> IO a -> IO a` into `withTransaction :: ... => m a -> m a` without modifying the source of `withTransaction`.

(Incidentally,  I'm not necessarily 100% opposed to breaking backward compatibility if there's a sufficiently compelling reason to do so,  but it's not something to be taken lightly.    I am considering the next evolution of the API,  but the issues I'm concerned with are rather different than the ones you are raising.)

**Comment by reiddraper** [comment]
Fwiw, I would not be in favor of _only_ exposing the postgresql-transactional interface. I like postgresql-simple how it is now, with the ability to layer things like postreql-transacitonal on top. If it came batteries included in postgresql-simple, that would be convenient, but nothing more.

**Comment by BardurArantsson** [comment]
Alright, I can certainly buy the arguments that there may be cases where you do want absolute control. (I think it might be better to instead have an "unsafe" API for that, though... So some sort of "inverse" of the current situation... but that's a completely different discussion.)

... and of course backward-compat *is* important.

So: It appears what we're looking at here then is "just" rewriting the postgresql-transactional module using `transformers` and adding it as a new module? (In terms of what's being proposed.)

**Comment by BardurArantsson** [comment]
Given that https://github.com/helium/postgresql-transactional/issues/1 was done, I think this is perhaps redundant? Closing as such. (I mean there's a *slight* inconvenience in 3rd party users of my library to have to build-depend on both postgresql-simple and postgresql-transactional, but it's not really a big deal.)

@lpsmith : Btw, it seems MonadBaseControl might be a solution to the "generalize beyond IO" problem?

**Comment by bitemyapp** [comment]
@BardurArantsson > Btw, it seems MonadBaseControl might be a solution to the "generalize beyond IO" problem?

In terms of power perhaps, but have you ever watched a non-expert Haskell user try to write one of those instances? It is maddeningly obnoxious and working examples are sparse.

The library itself generates the instances from _CPP_.

**Comment by BardurArantsson** [comment]
@bitemyapp No, but then I don't think users of the library will *have* to write any instances.

**Comment by bitemyapp** [comment]
@BardurArantsson any library introducing the constraint creates the possibility that anyone using their own Monad will have to write their own instances. I'd certainly run into that in the past when working on a 1.0 beta Snap application.

**Comment by BardurArantsson** [comment]
@bitemyapp Well, it's kind of essential complexity isn't it? (For the problem `monad-control` is trying to solve.)

Btw, somewhat counterintuitively, I usually find that going straight to MonadTrans and implementing a simple newtype wrapper around existing monad transformers is simpler than trying to actually implement a Monad. If you then just avoid exporting the constructor for your monad transformer's data type, you get the "you may only run operations X, Y, and Z" for free. (And of course the simple Monad version of your transformer you get by just substituting in Identity as the "base" monad. Just can always just provide that as a convenience `type` definition.)

If you use the transformer-stack-wrapped-in-newtype approach you basically get MonadTransControl for free; see [https://hackage.haskell.org/package/monad-control-1.0.0.1/docs/Control-Monad-Trans-Control.html](the CounterT example).

I literally cannot recall the last time I've had to "invent my own Monad{,Trans}" from scratch -- other than for educational purposes. Most things are really just combinations of RWSX.

(Anyway, for this particular use case you'd *have* to implement a transformer as far as I can see -- 'postgresql-simple` absolutely needs IO at the base anyway and there's no getting out of that. I mean you could use MonadIO, but then we're back at square one wrt. the issues @lpsmith outlined.)

Anyway, this is getting pretty off-topic, I'll stop now.

**Comment by bitemyapp** [comment]
@BardurArantsson I know how to use GND. I didn't have a choice in this case, I was working with a legacy codebase with a pre-established Monad and no time to fix or refactor anything. Unless you're volunteering to step in for people in that situation in future, please don't dismiss risks/costs/objections raised by others.

**Comment by BardurArantsson** [comment]
I'm not dismissing anything, just offering possible solutions. I have no way of knowing what your situation is/was. HAND :).
