### ISSUE TITLE
_int8 treated as incompatible with Int64, Integer, and Int executing a query - Stack Nightly 64 bit Linux

### ISSUE THREAD

**Issue by autcrock** [lpsmith/postgresql-simple#190]
Hi Leon.

I have reached the limit of my out-of-date Haskell debugging skills with this one, so reaching out for help.  

  [http://stackoverflow.com/questions/38735008/haskell-postgresql-simple-incompatible-type-int8-and-int64-and-integer
](url)

Hopefully it is nothing more than a misapprehension of the documentation on my part.

Cheers

Mike Thomas

**Comment by lpsmith** [comment]
Sure,  the underscore in `_int8` means it's an array of 8-byte integers.   So you need to change the return type to `[Only (Vector Int64)]`

**Comment by lpsmith** [comment]
Or,  don't call `_array_agg`,  which would probably be a somewhat better choice in this situation.

**Comment by autcrock** [comment]
Thanks Leon, not only for the answer which worked, but for your work on postgresql-simple which I am finding very helpful.

The _array_agg will go away soon.  It was a by product of my initial attempts to get the marshalling types correct.

**Comment by lpsmith** [comment]
You are welcome!

**Comment by lpsmith** [comment]
Looking at the `Database.PostgreSQL.Simple.FromField` documentation,  this isn't mentioned.  So that is  worth fixing.  

Unfortunately the underscore meaning "array of" is a convention;  I don't think it's a hard and fast rule.   I know that some of the older built in types have an associated array type that doesn't start with an underscore.  It's _probably_ possible to create a non-array type that starts with an underscore as well.  The more robust approach is checking the `pg_type`  table,  which contains metadata for every type (built in or not)

Try this query in `psql`:   `select oid, * from pg_type`;  the partial contents of this metatable is also accessible through postgresql-simple's [`TypeInfo`](https://hackage.haskell.org/package/postgresql-simple-0.5.2.1/docs/Database-PostgreSQL-Simple-TypeInfo.html) system.

**Comment by autcrock** [comment]
Thanks for that further information Leon.

I was the victim of ten years of C programming seeing the _ as an indicator
of an internal type, managing to convince myself it was on the Haskell
side, although I didn't see it as I skimmed through the postgres-simple
source code.

Cheers

Mike Thomas
